/**
 * Standardized Sourcing States & Statuses (v21.2 API-STRICT)
 */
export const SourcingStatus = {
  SUCCESS: 'SUCCESS',
  EMPTY: 'EMPTY',
  EMPTY_CATALOG_RESULT: 'EMPTY_CATALOG_RESULT',
  API_ERROR: 'API_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  AUTH_FAILURE: 'AUTH_FAILURE'
};

export const SourcingUIState = {
  IDLE: 'IDLE',
  // AliExpress States [API ONLY]
  ALIEXPRESS_SEARCHING: 'ALIEXPRESS_SEARCHING',
  ALIEXPRESS_SUCCESS: 'ALIEXPRESS_SUCCESS',
  ALIEXPRESS_EMPTY: 'ALIEXPRESS_EMPTY',
  ALIEXPRESS_ERROR: 'ALIEXPRESS_ERROR'
};
