/**
 * Standardized Sourcing States & Statuses
 */
export const SourcingStatus = {
  SUCCESS: 'SUCCESS',
  EMPTY: 'EMPTY',
  EMPTY_CATALOG_RESULT: 'EMPTY_CATALOG_RESULT',
  API_ERROR: 'API_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  BLOCKED: 'BLOCKED',
  BLOCKED_RESPONSE: 'BLOCKED_RESPONSE',
  PARSE_ERROR: 'PARSE_ERROR',
  PARSE_FAILURE: 'PARSE_FAILURE',
  AUTH_FAILURE: 'AUTH_FAILURE',
  EXTENSION_NOT_LOADED: 'EXTENSION_NOT_LOADED'
};

export const SourcingUIState = {
  IDLE: 'IDLE',
  // Eprolo States
  EPROLO_SEARCHING: 'EPROLO_SEARCHING',
  EPROLO_SUCCESS: 'EPROLO_SUCCESS',
  EPROLO_EMPTY: 'EPROLO_EMPTY',
  EPROLO_ERROR: 'EPROLO_ERROR',
  // AliExpress States
  ALIEXPRESS_SEARCHING: 'ALIEXPRESS_SEARCHING',
  ALIEXPRESS_SUCCESS: 'ALIEXPRESS_SUCCESS',
  ALIEXPRESS_EMPTY: 'ALIEXPRESS_EMPTY',
  ALIEXPRESS_BLOCKED: 'ALIEXPRESS_BLOCKED',
  ALIEXPRESS_ERROR: 'ALIEXPRESS_ERROR'
};
