name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install --legacy-peer-deps && npm run build
        env:
          VITE_EBAY_APP_ID: ${{ secrets.VITE_EBAY_APP_ID }}
          VITE_EBAY_CERT_ID: ${{ secrets.VITE_EBAY_CERT_ID }}
          VITE_EBAY_USER_TOKEN: ${{ secrets.VITE_EBAY_USER_TOKEN }}
          VITE_EPROLO_API_KEY: ${{ secrets.VITE_EPROLO_API_KEY }}
          VITE_EPROLO_API_SECRET: ${{ secrets.VITE_EPROLO_API_SECRET }}
          VITE_HF_API_KEY: ${{ secrets.VITE_HF_API_KEY }}
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_FIREBASE_API_KEY: "AIzaSyCL72g1xcMcuELRRRL4gmngeDdPO_ZZGnA"
          VITE_FIREBASE_AUTH_DOMAIN: "geonoyc-dropshipping.firebaseapp.com"
          VITE_FIREBASE_PROJECT_ID: "geonoyc-dropshipping"
          VITE_FIREBASE_STORAGE_BUCKET: "geonoyc-dropshipping.firebasestorage.app"
          VITE_FIREBASE_MESSAGING_SENDER_ID: "704927667189"
          VITE_FIREBASE_APP_ID: "1:704927667189:web:ba367bb776d8a11bb5c6bc"
          VITE_PROXY_URL: ${{ secrets.VITE_PROXY_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GEONOYC_DROPSHIPPING }}'
          channelId: live
          projectId: geonoyc-dropshipping
